# Generated by Django 4.1.1 on 2022-09-22 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_length', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hex_id', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('mother_last_name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'User',
                'db_table': 'User',
            },
        ),
    ]
