# Generated by Django 4.1.1 on 2022-09-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
